Epic3 (44)логика fav по слоям
andrei-urich/practicum-android-diploma pull request #49
Opened 2024-11-13 20:21 UTC by DimoonAndDev

#44

2024-11-14 10:12 UTC, andrei-urich requested changes
- Надо сделать интерактор интерфейс и его реализацию InteractorImpl (сейчас у тебя сразу реализация). Все это в домене, в том же месте.
- комментарии в коде (задвоение импорта в одном месте; если используешь Flow, то не нужен suspend)

2024-11-14 10:12 UTC, andrei-urich commented on app/src/main/java/ru/practicum/android/diploma/domain/interactors/FavoriteVacanciesInteractor.kt
> +    suspend fun getFavVacanciesList(): Flow<List<Vacancy>> {
suspend не нужно, т.к. возвращаемый тип Flow

2024-11-14 10:12 UTC, andrei-urich commented on app/src/main/java/ru/practicum/android/diploma/domain/repository/FavoriteVacanciesRepository.kt
> +    suspend fun getFavVacanciesList(): Flow<List<Vacancy>>
suspend не нужно, т.к. возвращаемый тип Flow

2024-11-14 19:00 UTC, DimoonAndDev commented on app/src/main/java/ru/practicum/android/diploma/data/repository/FavoriteVacanciesRepositoryImpl.kt
> +import kotlinx.coroutines.flow.flow
нет, тут Flow как тип и _flow_ как лямбда

2024-11-14 19:00 UTC, DimoonAndDev commented on app/src/main/java/ru/practicum/android/diploma/domain/interactors/FavoriteVacanciesInteractor.kt
> +    suspend fun getFavVacanciesList(): Flow<List<Vacancy>> {
убрал

2024-11-14 20:14 UTC, DimoonAndDev commented
был merge conflict, так как Вячеслав уже внес правки в DI. Я запулил актуальный develop и накатил уже только свои обновления.

2024-11-15 11:46 UTC, andrei-urich approved these changes

2024-11-15 11:46 UTC, merged